# Generated by Django 4.2.1 on 2023-11-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_request_chat"),
        (
            "power_chat",
            "0004_remove_powerchatmessage_chat_powerchatmessage_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerchatmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="power_messages",
                to="chats.userprofile",
            ),
        ),
    ]
