# Generated by Django 4.2.1 on 2023-11-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_request_chat"),
        ("power_chat", "0003_powerchat_conversation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="powerchatmessage",
            name="chat",
        ),
        migrations.AddField(
            model_name="powerchatmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="power_mesages",
                to="chats.userprofile",
            ),
        ),
        migrations.DeleteModel(
            name="PowerChat",
        ),
    ]
