# Generated by Django 4.2.1 on 2023-11-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_remove_answer_question_answer_chat_alter_chat_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_chat",
                to="chats.chat",
            ),
        ),
    ]
