# Generated by Django 4.2.1 on 2023-11-15 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_answer_chat_question_request_remove_chatsession_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="user",
        ),
        migrations.RemoveField(
            model_name="file",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="question",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="request",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="request",
            name="question",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Request",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
